// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT_WvD8xOcqneO3f5KwHxjhOR1oOvrctQ',
    appId: '1:275698361456:web:f33bd33a2f740f108940b5',
    messagingSenderId: '275698361456',
    projectId: 'myfirstproject-330f2',
    authDomain: 'myfirstproject-330f2.firebaseapp.com',
    storageBucket: 'myfirstproject-330f2.firebasestorage.app',
    measurementId: 'G-4J0NYFT5H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIzgHxqBS7egA-ghnXIHEBQWBlMeH2Swo',
    appId: '1:275698361456:android:baf9b4096427689b8940b5',
    messagingSenderId: '275698361456',
    projectId: 'myfirstproject-330f2',
    storageBucket: 'myfirstproject-330f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAvIJlo75_kIhk3VRGOoGI1g5g1Q7p7-A',
    appId: '1:275698361456:ios:d651a6cbe50dfa068940b5',
    messagingSenderId: '275698361456',
    projectId: 'myfirstproject-330f2',
    storageBucket: 'myfirstproject-330f2.firebasestorage.app',
    androidClientId: '275698361456-qpbf4psfv0d6vub5jj771o4n6i093n0o.apps.googleusercontent.com',
    iosClientId: '275698361456-mk4ogf1lk4abarj7la62m5fc1ha4d2lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.servup',
  );
}
