// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIzgHxqBS7egA-ghnXIHEBQWBlMeH2Swo',
    appId: '1:275698361456:android:a4b23f5d1c00c2f18940b5',
    messagingSenderId: '275698361456',
    projectId: 'myfirstproject-330f2',
    storageBucket: 'myfirstproject-330f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAvIJlo75_kIhk3VRGOoGI1g5g1Q7p7-A',
    appId: '1:275698361456:ios:97fb31938152db6b8940b5',
    messagingSenderId: '275698361456',
    projectId: 'myfirstproject-330f2',
    storageBucket: 'myfirstproject-330f2.firebasestorage.app',
    androidClientId: '275698361456-qpbf4psfv0d6vub5jj771o4n6i093n0o.apps.googleusercontent.com',
    iosClientId: '275698361456-62njet8ebsm4v94hq1sbacnna0njhj7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
